version: '2'
services:
  nginx:
    image: ggnanasekaran77/ggnanasekaran
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.{{.Name}}"

